apiVersion: apps/v1

kind: StatefulSet

metadata:
  name: statefulset-db

spec:
  serviceName: db
  selector:
    matchLabels:
      name: postgres

  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: container-postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: db-volume

---

apiVersion: v1

kind: PersistentVolumeClaim

metadata: 
  name: db-volume

spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi