apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-NEWVERSION
spec:
  selector:
    matchLabels:
      name: store
      version: "NEWVERSION"
  
  template:
    metadata:
      labels:
        name: store
        version: "NEWVERSION"
        
    spec:
      containers:
        - name: store
          image: alexdias/store:NEWVERSION
          env:
            - name: DB_HOST
              value: db
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3