apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-NEWVERSION
spec:
  selector:
    matchLabels:
      name: store
      version: "NEWVERSION"
  
  template:
    metadata:
      labels:
        name: store
        version: "NEWVERSION"
        
    spec:
      containers:
        - name: store
          image: alexdias/store:NEWVERSION
          env:
            - name: DB_USER
              value: postgres
            - name: DB_HOST
              value: store2.cjgfhctc7hg9.us-east-1.rds.amazonaws.com
            - name: DB_PASS
              value: postgres
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3